### ISSUE TITLE
Close toast on click

### ISSUE THREAD

**Issue by Hesesses** [rajeshwarpatlolla/ionic-toast#5]
Hi,

Is it possible to close the toast when you click? Instead of clicking the small X

**Comment by rajeshwarpatlolla** [comment]
For now, there is no such feature. This might make the user feel weird. Few user might want to click just to see the message. So thinking of such aspects, i haven't implemented this feature.

**Comment by Hesesses** [comment]
What about making it optional parameter?

**Comment by vishalbhingaradiya** [comment]
Hi,

I have a alternate solution for close the toast when you click on the toast Instead of clicking the small X.
you can small change into the ionic-master.js 

check the below image, you can add only ng-click into the parent div so it's will manage easily

![ionic-toast-change](https://cloud.githubusercontent.com/assets/6336486/12050492/6ff8cb8c-af1c-11e5-8de3-2d6c9a52c591.png)

May this will help you!
Thanks
